/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

const documents = {
    "mutation InsertUserOne($username: String!, $slug: String!) {\n  insert_user_one(object: {username: $username, canvas_slug: $slug}) {\n    id\n    username\n    canvas_slug\n  }\n}": types.InsertUserOneDocument,
    "query CheckUser($username: String) {\n  user(where: {username: {_eq: $username}}) {\n    id\n    username\n  }\n}": types.CheckUserDocument,
    "subscription GetAllMessages($canvas_slug: String) {\n  canvas(where: {slug: {_eq: $canvas_slug}}) {\n    messages {\n      shape\n      color\n      id\n      user {\n        username\n      }\n    }\n  }\n}": types.GetAllMessagesDocument,
    "query GetColors {\n  colors {\n    value\n  }\n}": types.GetColorsDocument,
    "subscription ColorsAggregate($red: colors_enum, $green: colors_enum, $blue: colors_enum, $yellow: colors_enum, $slug: String) {\n  canvas(where: {slug: {_eq: $slug}}) {\n    red: messages_aggregate(where: {color: {_eq: $red}}) {\n      aggregate {\n        count\n      }\n    }\n    green: messages_aggregate(where: {color: {_eq: $green}}) {\n      aggregate {\n        count\n      }\n    }\n    blue: messages_aggregate(where: {color: {_eq: $blue}}) {\n      aggregate {\n        count\n      }\n    }\n    yellow: messages_aggregate(where: {color: {_eq: $yellow}}) {\n      aggregate {\n        count\n      }\n    }\n  }\n}": types.ColorsAggregateDocument,
    "subscription ShapesAggregate($circle: shapes_enum, $square: shapes_enum, $triangle: shapes_enum, $octagon: shapes_enum, $poly: shapes_enum, $slug: String) {\n  canvas(where: {slug: {_eq: $slug}}) {\n    circle: messages_aggregate(where: {shape: {_eq: $circle}}) {\n      aggregate {\n        count\n      }\n    }\n    square: messages_aggregate(where: {shape: {_eq: $square}}) {\n      aggregate {\n        count\n      }\n    }\n    triangle: messages_aggregate(where: {shape: {_eq: $triangle}}) {\n      aggregate {\n        count\n      }\n    }\n    octagon: messages_aggregate(where: {shape: {_eq: $octagon}}) {\n      aggregate {\n        count\n      }\n    }\n    poly: messages_aggregate(where: {shape: {_eq: $poly}}) {\n      aggregate {\n        count\n      }\n    }\n  }\n}": types.ShapesAggregateDocument,
    "mutation CreateCanvas($slug: String) {\n  insert_canvas_one(object: {slug: $slug}) {\n    id\n  }\n}": types.CreateCanvasDocument,
    "subscription EventStream($slug: String, $date: timestamptz) {\n  canvas_message_stream(\n    where: {canvas_slug: {_eq: $slug}}\n    batch_size: 3\n    cursor: {ordering: ASC, initial_value: {updated_at: $date}}\n  ) {\n    id\n    color\n    shape\n  }\n}": types.EventStreamDocument,
    "mutation UpsertMessage($shape: shapes_enum, $color: colors_enum) {\n  insert_canvas_message_one(\n    object: {shape: $shape, color: $color}\n    on_conflict: {constraint: game_message_pkey, update_columns: color}\n  ) {\n    id\n  }\n}": types.UpsertMessageDocument,
    "query GetShapes {\n  shapes {\n    value\n  }\n}": types.GetShapesDocument,
};

export function graphql(source: "mutation InsertUserOne($username: String!, $slug: String!) {\n  insert_user_one(object: {username: $username, canvas_slug: $slug}) {\n    id\n    username\n    canvas_slug\n  }\n}"): (typeof documents)["mutation InsertUserOne($username: String!, $slug: String!) {\n  insert_user_one(object: {username: $username, canvas_slug: $slug}) {\n    id\n    username\n    canvas_slug\n  }\n}"];
export function graphql(source: "query CheckUser($username: String) {\n  user(where: {username: {_eq: $username}}) {\n    id\n    username\n  }\n}"): (typeof documents)["query CheckUser($username: String) {\n  user(where: {username: {_eq: $username}}) {\n    id\n    username\n  }\n}"];
export function graphql(source: "subscription GetAllMessages($canvas_slug: String) {\n  canvas(where: {slug: {_eq: $canvas_slug}}) {\n    messages {\n      shape\n      color\n      id\n      user {\n        username\n      }\n    }\n  }\n}"): (typeof documents)["subscription GetAllMessages($canvas_slug: String) {\n  canvas(where: {slug: {_eq: $canvas_slug}}) {\n    messages {\n      shape\n      color\n      id\n      user {\n        username\n      }\n    }\n  }\n}"];
export function graphql(source: "query GetColors {\n  colors {\n    value\n  }\n}"): (typeof documents)["query GetColors {\n  colors {\n    value\n  }\n}"];
export function graphql(source: "subscription ColorsAggregate($red: colors_enum, $green: colors_enum, $blue: colors_enum, $yellow: colors_enum, $slug: String) {\n  canvas(where: {slug: {_eq: $slug}}) {\n    red: messages_aggregate(where: {color: {_eq: $red}}) {\n      aggregate {\n        count\n      }\n    }\n    green: messages_aggregate(where: {color: {_eq: $green}}) {\n      aggregate {\n        count\n      }\n    }\n    blue: messages_aggregate(where: {color: {_eq: $blue}}) {\n      aggregate {\n        count\n      }\n    }\n    yellow: messages_aggregate(where: {color: {_eq: $yellow}}) {\n      aggregate {\n        count\n      }\n    }\n  }\n}"): (typeof documents)["subscription ColorsAggregate($red: colors_enum, $green: colors_enum, $blue: colors_enum, $yellow: colors_enum, $slug: String) {\n  canvas(where: {slug: {_eq: $slug}}) {\n    red: messages_aggregate(where: {color: {_eq: $red}}) {\n      aggregate {\n        count\n      }\n    }\n    green: messages_aggregate(where: {color: {_eq: $green}}) {\n      aggregate {\n        count\n      }\n    }\n    blue: messages_aggregate(where: {color: {_eq: $blue}}) {\n      aggregate {\n        count\n      }\n    }\n    yellow: messages_aggregate(where: {color: {_eq: $yellow}}) {\n      aggregate {\n        count\n      }\n    }\n  }\n}"];
export function graphql(source: "subscription ShapesAggregate($circle: shapes_enum, $square: shapes_enum, $triangle: shapes_enum, $octagon: shapes_enum, $poly: shapes_enum, $slug: String) {\n  canvas(where: {slug: {_eq: $slug}}) {\n    circle: messages_aggregate(where: {shape: {_eq: $circle}}) {\n      aggregate {\n        count\n      }\n    }\n    square: messages_aggregate(where: {shape: {_eq: $square}}) {\n      aggregate {\n        count\n      }\n    }\n    triangle: messages_aggregate(where: {shape: {_eq: $triangle}}) {\n      aggregate {\n        count\n      }\n    }\n    octagon: messages_aggregate(where: {shape: {_eq: $octagon}}) {\n      aggregate {\n        count\n      }\n    }\n    poly: messages_aggregate(where: {shape: {_eq: $poly}}) {\n      aggregate {\n        count\n      }\n    }\n  }\n}"): (typeof documents)["subscription ShapesAggregate($circle: shapes_enum, $square: shapes_enum, $triangle: shapes_enum, $octagon: shapes_enum, $poly: shapes_enum, $slug: String) {\n  canvas(where: {slug: {_eq: $slug}}) {\n    circle: messages_aggregate(where: {shape: {_eq: $circle}}) {\n      aggregate {\n        count\n      }\n    }\n    square: messages_aggregate(where: {shape: {_eq: $square}}) {\n      aggregate {\n        count\n      }\n    }\n    triangle: messages_aggregate(where: {shape: {_eq: $triangle}}) {\n      aggregate {\n        count\n      }\n    }\n    octagon: messages_aggregate(where: {shape: {_eq: $octagon}}) {\n      aggregate {\n        count\n      }\n    }\n    poly: messages_aggregate(where: {shape: {_eq: $poly}}) {\n      aggregate {\n        count\n      }\n    }\n  }\n}"];
export function graphql(source: "mutation CreateCanvas($slug: String) {\n  insert_canvas_one(object: {slug: $slug}) {\n    id\n  }\n}"): (typeof documents)["mutation CreateCanvas($slug: String) {\n  insert_canvas_one(object: {slug: $slug}) {\n    id\n  }\n}"];
export function graphql(source: "subscription EventStream($slug: String, $date: timestamptz) {\n  canvas_message_stream(\n    where: {canvas_slug: {_eq: $slug}}\n    batch_size: 3\n    cursor: {ordering: ASC, initial_value: {updated_at: $date}}\n  ) {\n    id\n    color\n    shape\n  }\n}"): (typeof documents)["subscription EventStream($slug: String, $date: timestamptz) {\n  canvas_message_stream(\n    where: {canvas_slug: {_eq: $slug}}\n    batch_size: 3\n    cursor: {ordering: ASC, initial_value: {updated_at: $date}}\n  ) {\n    id\n    color\n    shape\n  }\n}"];
export function graphql(source: "mutation UpsertMessage($shape: shapes_enum, $color: colors_enum) {\n  insert_canvas_message_one(\n    object: {shape: $shape, color: $color}\n    on_conflict: {constraint: game_message_pkey, update_columns: color}\n  ) {\n    id\n  }\n}"): (typeof documents)["mutation UpsertMessage($shape: shapes_enum, $color: colors_enum) {\n  insert_canvas_message_one(\n    object: {shape: $shape, color: $color}\n    on_conflict: {constraint: game_message_pkey, update_columns: color}\n  ) {\n    id\n  }\n}"];
export function graphql(source: "query GetShapes {\n  shapes {\n    value\n  }\n}"): (typeof documents)["query GetShapes {\n  shapes {\n    value\n  }\n}"];

export function graphql(source: string): unknown;
export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;